### ISSUE TITLE
xcb] Unknown request in queue while dequeuing

### ISSUE THREAD

**Issue by TheOncomingStorm** [cjcliffe/CubicSDR#254]
I'm using Gentoo 64-bit. 

Full error is:
```
./build/x64/CubicSDR
SDR post-processing thread started..Spectrum visual data thread started.

Spectrum visual data thread started.
FFT visual data thread started.

Audio Device #0 PulseAudio
        Default Output? Yes
        Default Input? Yes
        Input channels: 2
        Output channels: 2
        Duplex channels: 2
        Native formats:
                16-bit signed integer.
                32-bit signed integer.
                32-bit float normalized between plus/minus 1.0.
        Supported sample rates:
                8000hz
                16000hz
                22050hz
                32000hz
                44100hz
                48000hz
                96000hz

Available vertical sync SwapInterval functions: 
        glxSwapIntervalEXT: No
        DRI2SwapInterval: No
        glxSwapIntervalMESA: No
        glxSwapIntervalSGI: No
No vertical sync swap interval functions available.
Loaded font 'Bitstream Vera Sans Mono' from '/home/user/src/CubicSDR/build/x64/vera_sans_mono16.fnt', parsed 167 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/home/user/src/CubicSDR/build/x64/vera_sans_mono12.fnt', parsed 167 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/home/user/src/CubicSDR/build/x64/vera_sans_mono18.fnt', parsed 167 characters.
SDR enumerator starting.
SoapySDR init..
        API Version: v0.4.0-gd17177f3
        ABI Version: v0.4-2
        Install root: /usr
        Loading modules... 
        Available factories...nullJust 'null' factory found.
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
CubicSDR: /var/tmp/portage/x11-libs/libX11-1.6.3/work/libX11-1.6.3/src/xcb_io.c:179: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
Aborted

```

http://stackoverflow.com/questions/31952711/threading-pyqt-crashes-with-unknown-request-in-queue-while-dequeuing
This suggests it's an issue with XInitThreads needing to be specifically set to be threadsafe in PyQt.

**Comment by TheOncomingStorm** [comment]
Here's a backtrace if that helps. 

```
gdb ./build/x64/CubicSDR
GNU gdb (Gentoo 7.10 vanilla) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./build/x64/CubicSDR...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/eric/src/CubicSDR/build/x64/CubicSDR 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe9f43700 (LWP 19440)]
SDR post-processing thread started..
[New Thread 0x7fffe9742700 (LWP 19441)]
Spectrum visual data thread started.
[New Thread 0x7fffe8f41700 (LWP 19442)]
Spectrum visual data thread started.
[New Thread 0x7fffd35d7700 (LWP 19443)]
FFT visual data thread started.

Audio Device #0 PulseAudio
        Default Output? Yes
        Default Input? Yes
        Input channels: 2
        Output channels: 2
        Duplex channels: 2
        Native formats:
                16-bit signed integer.
                32-bit signed integer.
                32-bit float normalized between plus/minus 1.0.
        Supported sample rates:
                8000hz
                16000hz
                22050hz
                32000hz
                44100hz
                48000hz
                96000hz

Available vertical sync SwapInterval functions: 
        glxSwapIntervalEXT: No
        DRI2SwapInterval: No
        glxSwapIntervalMESA: No
        glxSwapIntervalSGI: No
No vertical sync swap interval functions available.
Loaded font 'Bitstream Vera Sans Mono' from '/home/user/src/CubicSDR/build/x64/vera_sans_mono16.fnt', parsed 167 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/home/user/src/CubicSDR/build/x64/vera_sans_mono12.fnt', parsed 167 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/home/user/src/CubicSDR/build/x64/vera_sans_mono18.fnt', parsed 167 characters.
[New Thread 0x7fffd19d6700 (LWP 19444)]
SDR enumerator starting.
SoapySDR init..
        API Version: v0.4.0-gd17177f3
        ABI Version: v0.4-2
        Install root: /usr
        Loading modules... 
        Available factories...nullJust 'null' factory found.
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
CubicSDR: /var/tmp/portage/x11-libs/libX11-1.6.3/work/libX11-1.6.3/src/xcb_io.c:179: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffd19d6700 (LWP 19444)]
0x00007ffff4429096 in raise () from /lib64/libc.so.6
(gdb) backtrace
#0  0x00007ffff4429096 in raise () from /lib64/libc.so.6
#1  0x00007ffff442a680 in abort () from /lib64/libc.so.6
#2  0x00007ffff4421b84 in ?? () from /lib64/libc.so.6
#3  0x00007ffff4421c3a in __assert_fail () from /lib64/libc.so.6
#4  0x00007ffff35977d2 in ?? () from /usr/lib64/libX11.so.6
#5  0x00007ffff35986f9 in _XReply () from /usr/lib64/libX11.so.6
#6  0x00007ffff358288e in XInternAtom () from /usr/lib64/libX11.so.6
#7  0x00007ffff3b46558 in gdk_x11_atom_to_xatom_for_display () from /usr/lib64/libgdk-x11-2.0.so.0
#8  0x00007ffff3b3b6ce in gdk_x11_get_server_time () from /usr/lib64/libgdk-x11-2.0.so.0
#9  0x00007ffff402dea2 in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#10 0x00007ffff402df40 in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#11 0x00007ffff402e51f in gtk_clipboard_set_with_owner () from /usr/lib64/libgtk-x11-2.0.so.0
#12 0x00007ffff3ed033d in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#13 0x00007ffff3ed4f72 in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#14 0x00007ffff389e430 in ?? () from /usr/lib64/libgobject-2.0.so.0
#15 0x00007ffff38b4e87 in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#16 0x00007ffff38b567a in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#17 0x00007ffff4013590 in gtk_widget_grab_focus () from /usr/lib64/libgtk-x11-2.0.so.0
#18 0x00007ffff3ed046f in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#19 0x00007ffff3ee245c in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#20 0x00007ffff389e1f3 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#21 0x00007ffff38b0aed in ?? () from /usr/lib64/libgobject-2.0.so.0
#22 0x00007ffff38b543b in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#23 0x00007ffff38b567a in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#24 0x00007ffff4014125 in gtk_widget_child_focus () from /usr/lib64/libgtk-x11-2.0.so.0
#25 0x00007ffff3e55073 in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#26 0x00007ffff3ee245c in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#27 0x00007ffff389e1f3 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#28 0x00007ffff38b0aed in ?? () from /usr/lib64/libgobject-2.0.so.0
#29 0x00007ffff38b543b in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#30 0x00007ffff38b567a in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#31 0x00007ffff4014125 in gtk_widget_child_focus () from /usr/lib64/libgtk-x11-2.0.so.0
#32 0x00007ffff3e55073 in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#33 0x00007ffff3ee245c in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#34 0x00007ffff389e1f3 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#35 0x00007ffff38b0aed in ?? () from /usr/lib64/libgobject-2.0.so.0
#36 0x00007ffff38b543b in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#37 0x00007ffff38b567a in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#38 0x00007ffff4014125 in gtk_widget_child_focus () from /usr/lib64/libgtk-x11-2.0.so.0
#39 0x00007ffff3e55073 in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#40 0x00007ffff3ee245c in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#41 0x00007ffff389e1f3 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#42 0x00007ffff38b0aed in ?? () from /usr/lib64/libgobject-2.0.so.0
#43 0x00007ffff38b543b in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#44 0x00007ffff38b567a in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#45 0x00007ffff4014125 in gtk_widget_child_focus () from /usr/lib64/libgtk-x11-2.0.so.0
#46 0x00007ffff4025583 in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#47 0x00007ffff3ee245c in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#48 0x00007ffff389e1f3 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#49 0x00007ffff38b0aed in ?? () from /usr/lib64/libgobject-2.0.so.0
#50 0x00007ffff38b543b in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#51 0x00007ffff38b567a in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#52 0x00007ffff4014125 in gtk_widget_child_focus () from /usr/lib64/libgtk-x11-2.0.so.0
#53 0x00007ffff402534c in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#54 0x00007ffff389e1f3 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#55 0x00007ffff38b0aed in ?? () from /usr/lib64/libgobject-2.0.so.0
#56 0x00007ffff38b53f5 in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#57 0x00007ffff38b57d4 in g_signal_emit_by_name () from /usr/lib64/libgobject-2.0.so.0
#58 0x00007ffff3e566bf in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#59 0x00007ffff389e430 in ?? () from /usr/lib64/libgobject-2.0.so.0
#60 0x00007ffff38b4e87 in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#61 0x00007ffff38b567a in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#62 0x00007ffff4019a13 in gtk_widget_map () from /usr/lib64/libgtk-x11-2.0.so.0
#63 0x00007ffff402548a in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#64 0x00007ffff389e430 in ?? () from /usr/lib64/libgobject-2.0.so.0
#65 0x00007ffff38b4e87 in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#66 0x00007ffff38b567a in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#67 0x00007ffff4018d30 in gtk_widget_show () from /usr/lib64/libgtk-x11-2.0.so.0
#68 0x00007ffff3e578d5 in gtk_dialog_run () from /usr/lib64/libgtk-x11-2.0.so.0
#69 0x00007ffff70b92dc in wxMessageDialog::ShowModal() () from /usr/lib64/libwx_gtk2u_core-3.0.so.0
#70 0x000000000042358f in CubicSDR::sdrEnumThreadNotify(SDREnumerator::SDREnumState, std::string) ()
#71 0x000000000045ddc8 in SDREnumerator::enumerate_devices(std::string, bool) ()
#72 0x000000000045e475 in SDREnumerator::run() ()
#73 0x00007ffff4f7b5a0 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6
#74 0x00007ffff479b428 in start_thread () from /lib64/libpthread.so.0
#75 0x00007ffff44e1edd in clone () from /lib64/libc.so.6

```

**Comment by cjcliffe** [comment]
@TheOncomingStorm that's perfect thanks; I think I know what's doing that and can make a patch to prevent it.

**Comment by cjcliffe** [comment]
@TheOncomingStorm I've committed a fix, it's happened before -- basically a modal dialog was trying to be spawned from a background thread and the window manager said no..

To answer why you got that dialog in the first place is written on the dialog itself; please let me know if it works and then let me know if it was an appropriate dialog for the situation :)

**Comment by TheOncomingStorm** [comment]
Yep, that helped tremendously and I was able to fix the situation appropriately. 

Thanks

**Comment by cjcliffe** [comment]
Good to hear it works as expected :+1: thanks for helping fix that up.
