### ISSUE TITLE
0.2.5 core dumps on exit

### ISSUE THREAD

**Issue by mrspirytus** [cjcliffe/CubicSDR#912]
Hello,

While looking at another issue (no audio) I started CubeSDR from the terminal to check if there are any errors printed to the terminal. I noticed that CubeSDR dumps every time on exit.

Ubuntu Mate 20.04 x64 (with Compiz)
```
Linux workbox 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
CubeSDR 0.2.5
```
 $ ldd /usr/bin/CubicSDR
	linux-vdso.so.1 (0x00007fff7ff0f000)
	libhamlib.so.2 => /lib/x86_64-linux-gnu/libhamlib.so.2 (0x00007fabb00a0000)
	libliquid.so.2d => /lib/x86_64-linux-gnu/libliquid.so.2d (0x00007fabaffbb000)
	libwx_gtk3u_gl-3.0.so.0 => /lib/x86_64-linux-gnu/libwx_gtk3u_gl-3.0.so.0 (0x00007fabaffa1000)
	libwx_gtk3u_core-3.0.so.0 => /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0 (0x00007fabaf91d000)
	libwx_gtk3u_propgrid-3.0.so.0 => /lib/x86_64-linux-gnu/libwx_gtk3u_propgrid-3.0.so.0 (0x00007fabaf822000)
	libwx_baseu-3.0.so.0 => /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0 (0x00007fabaf55e000)
	libOpenGL.so.0 => /lib/x86_64-linux-gnu/libOpenGL.so.0 (0x00007fabaf530000)
	libGLX.so.0 => /lib/x86_64-linux-gnu/libGLX.so.0 (0x00007fabaf4fc000)
	libSoapySDR.so.0.7 => /lib/x86_64-linux-gnu/libSoapySDR.so.0.7 (0x00007fabaf499000)
	libtinyxml.so.2.6.2 => /lib/x86_64-linux-gnu/libtinyxml.so.2.6.2 (0x00007fabaf481000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fabaf47b000)
	librtaudio.so.6 => /lib/x86_64-linux-gnu/librtaudio.so.6 (0x00007fabaf45d000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fabaf279000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fabaf12a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fabaf10f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fabaf0ec000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fabaeefa000)
	libusb-1.0.so.0 => /lib/x86_64-linux-gnu/libusb-1.0.so.0 (0x00007fabaeede000)
	libfftw3f.so.3 => /lib/x86_64-linux-gnu/libfftw3f.so.3 (0x00007fabaeccc000)
	libgtk-3.so.0 => /lib/x86_64-linux-gnu/libgtk-3.so.0 (0x00007fabae51b000)
	libgdk-3.so.0 => /lib/x86_64-linux-gnu/libgdk-3.so.0 (0x00007fabae416000)
	libcairo.so.2 => /lib/x86_64-linux-gnu/libcairo.so.2 (0x00007fabae2f3000)
	libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fabae293000)
	libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007fabae156000)
	libGL.so.1 => /lib/x86_64-linux-gnu/libGL.so.1 (0x00007fabae0cc000)
	libpangocairo-1.0.so.0 => /lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007fabae0ba000)
	libpango-1.0.so.0 => /lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007fabae06b000)
	libgdk_pixbuf-2.0.so.0 => /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007fabae043000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fabadf1a000)
	libSM.so.6 => /lib/x86_64-linux-gnu/libSM.so.6 (0x00007fabadf0f000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fabaded5000)
	libjpeg.so.8 => /lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007fabade50000)
	libtiff.so.5 => /lib/x86_64-linux-gnu/libtiff.so.5 (0x00007fabaddcf000)
	libwx_gtk3u_adv-3.0.so.0 => /lib/x86_64-linux-gnu/libwx_gtk3u_adv-3.0.so.0 (0x00007fabadbe2000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fabadbc6000)
	libGLdispatch.so.0 => /lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007fabadb0c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fabb06a9000)
	libpulse-simple.so.0 => /lib/x86_64-linux-gnu/libpulse-simple.so.0 (0x00007fabadb05000)
	libasound.so.2 => /lib/x86_64-linux-gnu/libasound.so.2 (0x00007fabada0a000)
	libjack.so.0 => /lib/x86_64-linux-gnu/libjack.so.0 (0x00007fabad9be000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007fabad991000)
	libgmodule-2.0.so.0 => /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fabad989000)
	libXi.so.6 => /lib/x86_64-linux-gnu/libXi.so.6 (0x00007fabad977000)
	libXfixes.so.3 => /lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fabad96f000)
	libcairo-gobject.so.2 => /lib/x86_64-linux-gnu/libcairo-gobject.so.2 (0x00007fabad963000)
	libatk-1.0.so.0 => /lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007fabad939000)
	libatk-bridge-2.0.so.0 => /lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0 (0x00007fabad902000)
	libepoxy.so.0 => /lib/x86_64-linux-gnu/libepoxy.so.0 (0x00007fabad7cd000)
	libfribidi.so.0 => /lib/x86_64-linux-gnu/libfribidi.so.0 (0x00007fabad7b0000)
	libgio-2.0.so.0 => /lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007fabad5cf000)
	libpangoft2-1.0.so.0 => /lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007fabad5b6000)
	libharfbuzz.so.0 => /lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fabad4b1000)
	libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fabad46a000)
	libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fabad3a9000)
	libXinerama.so.1 => /lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007fabad3a4000)
	libXrandr.so.2 => /lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007fabad397000)
	libXcursor.so.1 => /lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007fabad38a000)
	libXcomposite.so.1 => /lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007fabad385000)
	libXdamage.so.1 => /lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007fabad380000)
	libxkbcommon.so.0 => /lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007fabad33c000)
	libwayland-cursor.so.0 => /lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007fabad331000)
	libwayland-egl.so.1 => /lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007fabad32c000)
	libwayland-client.so.0 => /lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007fabad31b000)
	libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007fabad306000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fabad2fb000)
	libpixman-1.so.0 => /lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007fabad252000)
	libxcb-shm.so.0 => /lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007fabad24d000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fabad223000)
	libxcb-render.so.0 => /lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007fabad214000)
	libXrender.so.1 => /lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fabad00a000)
	libffi.so.7 => /lib/x86_64-linux-gnu/libffi.so.7 (0x00007fabacffc000)
	libthai.so.0 => /lib/x86_64-linux-gnu/libthai.so.0 (0x00007fabacff1000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fabacf7e000)
	libICE.so.6 => /lib/x86_64-linux-gnu/libICE.so.6 (0x00007fabacf60000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fabacf57000)
	libwebp.so.6 => /lib/x86_64-linux-gnu/libwebp.so.6 (0x00007fabaceeb000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007fabace42000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fabace19000)
	libjbig.so.0 => /lib/x86_64-linux-gnu/libjbig.so.0 (0x00007fabacc0b000)
	libnotify.so.4 => /lib/x86_64-linux-gnu/libnotify.so.4 (0x00007fabacc00000)
	libpulse.so.0 => /lib/x86_64-linux-gnu/libpulse.so.0 (0x00007fabacba9000)
	libpulsecommon-13.99.so => /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-13.99.so (0x00007fabacb27000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007fabacad6000)
	libatspi.so.0 => /lib/x86_64-linux-gnu/libatspi.so.0 (0x00007fabaca9f000)
	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007fabaca3f000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fabaca12000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fabac9f6000)
	libgraphite2.so.3 => /lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fabac9c9000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fabac99b000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007fabac995000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fabac98b000)
	libdatrie.so.1 => /lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007fabac981000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fabac967000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007fabac8b8000)
	libwrap.so.0 => /lib/x86_64-linux-gnu/libwrap.so.0 (0x00007fabac8ac000)
	libsndfile.so.1 => /lib/x86_64-linux-gnu/libsndfile.so.1 (0x00007fabac82c000)
	libasyncns.so.0 => /lib/x86_64-linux-gnu/libasyncns.so.0 (0x00007fabac626000)
	libapparmor.so.1 => /lib/x86_64-linux-gnu/libapparmor.so.1 (0x00007fabac611000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007fabac5ba000)
	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007fabac52a000)
	liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007fabac507000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fabac3e9000)
	libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007fabac3cc000)
	libFLAC.so.8 => /lib/x86_64-linux-gnu/libFLAC.so.8 (0x00007fabac38e000)
	libogg.so.0 => /lib/x86_64-linux-gnu/libogg.so.0 (0x00007fabac381000)
	libvorbis.so.0 => /lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007fabac353000)
	libvorbisenc.so.2 => /lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007fabac2a6000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fabac283000)

```

All messages printed when starting from Terminal
```
$ CubicSDR 
Loading:: configuration file '/home/mrspirytus/.CubicSDR/config.xml'
Loaded 230 rig models via hamlib.

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:0,0), Device or resource busy.


Audio Device #0 hw:HDA Intel PCH,0
	Default Output? No
	Default Input? Yes
	Input channels: 2
	Output channels: 0
	Duplex channels: 0
	Native formats:
		16-bit signed integer.
		32-bit signed integer.
	Supported sample rates:
		44100hz
		48000hz
		88200hz
		96000hz
		176400hz
		192000hz


Audio Device #1 hw:HDA Intel PCH,1
	Default Output? No
	Default Input? No
	Input channels: 0
	Output channels: 2
	Duplex channels: 0
	Native formats:
		16-bit signed integer.
		32-bit signed integer.
	Supported sample rates:
		32000hz
		44100hz
		48000hz
		88200hz
		96000hz
		192000hz


Audio Device #2 hw:HDA Intel PCH,2
	Default Output? No
	Default Input? No
	Input channels: 2
	Output channels: 0
	Duplex channels: 0
	Native formats:
		16-bit signed integer.
		32-bit signed integer.
	Supported sample rates:
		44100hz
		48000hz
		88200hz
		96000hz
		176400hz
		192000hz


Audio Device #3 hw:Logitech StreamCam,0
	Default Output? No
	Default Input? No
	Input channels: 2
	Output channels: 0
	Duplex channels: 0
	Native formats:
		16-bit signed integer.
	Supported sample rates:
		16000hz
		32000hz
		48000hz


Audio Device #4 hw:HDA NVidia,3
	Default Output? No
	Default Input? No
	Input channels: 0
	Output channels: 8
	Duplex channels: 0
	Native formats:
		16-bit signed integer.
		32-bit signed integer.
	Supported sample rates:
		32000hz
		44100hz
		48000hz
		88200hz
		96000hz
		176400hz
		192000hz


Audio Device #5 hw:HDA NVidia,7
	Default Output? No
	Default Input? No
	Input channels: 0
	Output channels: 2
	Duplex channels: 0
	Native formats:
		16-bit signed integer.
		32-bit signed integer.
	Supported sample rates:
		32000hz
		44100hz
		48000hz


Audio Device #6 hw:HDA NVidia,8
	Default Output? No
	Default Input? No
	Input channels: 0
	Output channels: 8
	Duplex channels: 0
	Native formats:
		16-bit signed integer.
		32-bit signed integer.
	Supported sample rates:
		32000hz
		44100hz
		48000hz
		88200hz
		96000hz
		176400hz
		192000hz


Audio Device #7 hw:HDA NVidia,9
	Default Output? No
	Default Input? No
	Input channels: 0
	Output channels: 8
	Duplex channels: 0
	Native formats:
		16-bit signed integer.
		32-bit signed integer.
	Supported sample rates:
		32000hz
		44100hz
		48000hz
		88200hz
		96000hz
		176400hz
		192000hz


Audio Device #8 hw:HDA NVidia,10
	Default Output? No
	Default Input? No
	Input channels: 0
	Output channels: 8
	Duplex channels: 0
	Native formats:
		16-bit signed integer.
		32-bit signed integer.
	Supported sample rates:
		32000hz
		44100hz
		48000hz
		88200hz
		96000hz
		176400hz
		192000hz


Audio Device #9 hw:HDA NVidia,11
	Default Output? No
	Default Input? No
	Input channels: 0
	Output channels: 8
	Duplex channels: 0
	Native formats:
		16-bit signed integer.
		32-bit signed integer.
	Supported sample rates:
		32000hz
		44100hz
		48000hz
		88200hz
		96000hz
		176400hz
		192000hz


Audio Device #10 hw:HDA NVidia,12
	Default Output? No
	Default Input? No
	Input channels: 0
	Output channels: 8
	Duplex channels: 0
	Native formats:
		16-bit signed integer.
		32-bit signed integer.
	Supported sample rates:
		32000hz
		44100hz
		48000hz
		88200hz
		96000hz
		176400hz
		192000hz


Audio Device #11 default
	Default Output? No
	Default Input? No
	Input channels: 32
	Output channels: 32
	Duplex channels: 32
	Native formats:
		16-bit signed integer.
		24-bit signed integer.
		32-bit signed integer.
		32-bit float normalized between plus/minus 1.0.
	Supported sample rates:
		4000hz
		5512hz
		8000hz
		9600hz
		11025hz
		16000hz
		22050hz
		32000hz
		44100hz
		48000hz
		88200hz
		96000hz
		176400hz
		192000hz

SDR enumerator starting.
SoapySDR init..
	API Version: v0.7.1
	ABI Version: v0.7
	Install root: /usr
	Loading modules... 
	Available factories...airspy, audio, bladerf, hackrf, lime, null, osmosdr, redpitaya, remote, rtlsdr, uhd
[INFO] [UHD] linux; GNU C++ version 9.2.1 20200304; Boost_107100; UHD_3.15.0.0-2build5

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:0,0), Device or resource busy.

Available vertical sync SwapInterval functions: 
	glxSwapIntervalEXT: Yes
	DRI2SwapInterval: No
	glxSwapIntervalMESA: Yes
	glxSwapIntervalSGI: Yes
Using glxSwapIntervalEXT.

Loaded font 'Bitstream Vera Sans Mono' from '/usr/share/cubicsdr/fonts/vera_sans_mono12_0.png', parsed 255 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/share/cubicsdr/fonts/vera_sans_mono16_0.png', parsed 255 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/share/cubicsdr/fonts/vera_sans_mono18_0.png', parsed 255 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/share/cubicsdr/fonts/vera_sans_mono24_0.png', parsed 255 characters.
Detached kernel driver
Loaded font 'Bitstream Vera Sans Mono' from '/usr/share/cubicsdr/fonts/vera_sans_mono27_0.png', parsed 255 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/share/cubicsdr/fonts/vera_sans_mono32_0.png', parsed 255 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/share/cubicsdr/fonts/vera_sans_mono36_0.png', parsed 255 characters.
Found Rafael Micro R820T tuner
Reattached kernel driver
  default_input = True
  default_output = False
  device_id = 0
  driver = audio
  label = hw:HDA Intel PCH,0
Make device 0

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:0,0), Device or resource busy.


RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:0,0), Device or resource busy.

  device_id=0
  origin=https://github.com/pothosware/SoapyAudio

  default_input = False
  default_output = False
  device_id = 2
  driver = audio
  label = hw:HDA Intel PCH,2
Make device 1

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:0,0), Device or resource busy.

  device_id=2
  origin=https://github.com/pothosware/SoapyAudio

  default_input = False
  default_output = False
  device_id = 3
  driver = audio
  label = hw:Logitech StreamCam,0
Make device 2

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:0,0), Device or resource busy.

  device_id=3
  origin=https://github.com/pothosware/SoapyAudio

  default_input = False
  default_output = False
  device_id = 11
  driver = audio
  label = default
Make device 3

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:0,0), Device or resource busy.

  device_id=11
  origin=https://github.com/pothosware/SoapyAudio

  device = HackRF One
  driver = hackrf
  label = HackRF One #0 c83868dc2c4576a3
  part_id = a000cb3c03504867e
  serial = 0000000000000000c83868dc2c4576a3
  version = 2021.03.1
Make device 4
[INFO] Opening HackRF One #0 c83868dc2c4576a3...
  clock source=internal
  part id=a000cb3c0504867e
  serial=0000000000000000c83868dc2c4576a3
  version=2021.03.1

  available = Yes
  driver = rtlsdr
  label = Generic RTL2832U OEM :: 00000001
  manufacturer = Realtek
  product = RTL2838UHIDIR
  rtl = 0
  serial = 00000001
  tuner = Rafael Micro R820T
Make device 5
Detached kernel driver
Found Rafael Micro R820T tuner
  origin=https://github.com/pothosware/SoapyRTLSDR
  rtl=0
Reattached kernel driver


Reporting enumeration complete.
SDR enumerator done.
[INFO] Opening HackRF One #0 c83868dc2c4576a3...
Detached kernel driver
Found Rafael Micro R820T tuner
SDR thread starting.
device init()
[INFO] Using format CF32.
Device Stream MTU: 131072
[R82XX] PLL not locked!
Allocating 15 zero-copy buffers
Disabled direct sampling mode
starting readLoop()
Error, device sample rate wasn't initialized?
Terminating SDR thread..
SDRThread::readStream(): 3.1 iqDataOutQueue output queue is full, discard processing of the batch...
readLoop() ended.
device deinit()
SDR thread done.
Terminating SDR post-processing thread..
Terminating All Demodulators..
Terminating Visual Processor threads..
Segmentation fault (core dumped)

```

My ~/.CubeSDR/config.xml
```
<?xml version="1.0" ?>
<cubicsdr_config>
    <window>
        <x>0</x>
        <y>55</y>
        <w>5120</w>
        <h>1304</h>
        <max>1</max>
        <tips>1</tips>
        <perf_mode>1</perf_mode>
        <theme>0</theme>
        <font_scale>1</font_scale>
        <snap>1</snap>
        <center_freq>92548150</center_freq>
        <waterfall_lps>25</waterfall_lps>
        <spectrum_avg>0.518219</spectrum_avg>
        <modemprops_collapsed>0</modemprops_collapsed>
        <db_offset>0</db_offset>
        <main_split>357</main_split>
        <vis_split>552</vis_split>
        <bookmark_split>391</bookmark_split>
        <bookmark_visible>1</bookmark_visible>
    </window>
    <recording>
        <path></path>
        <squelch>0</squelch>
        <file_time_limit>0</file_time_limit>
    </recording>
    <devices>
        <device>
            <id>Generic RTL2832U OEM ::</id>
            <name></name>
            <ppm>0</ppm>
            <offset>0</offset>
            <sample_rate>2560000</sample_rate>
            <agc_mode>1</agc_mode>
            <streamOpts>
                <asyncBuffs>0</asyncBuffs>
                <buffers>15</buffers>
                <bufflen>262144</bufflen>
            </streamOpts>
            <settings>
                <digital_agc>false</digital_agc>
                <direct_samp>0</direct_samp>
                <iq_swap>false</iq_swap>
                <offset_tune>false</offset_tune>
            </settings>
        </device>
        <device>
            <id>Generic RTL2832U OEM :: 00000001</id>
            <name></name>
            <ppm>0</ppm>
            <offset>0</offset>
            <sample_rate>2560000</sample_rate>
            <agc_mode>1</agc_mode>
            <streamOpts>
                <asyncBuffs>0</asyncBuffs>
                <buffers>15</buffers>
                <bufflen>262144</bufflen>
            </streamOpts>
            <settings>
                <digital_agc>false</digital_agc>
                <direct_samp>0</direct_samp>
                <iq_swap>false</iq_swap>
                <offset_tune>false</offset_tune>
            </settings>
            <gains>
                <gain>
                    <id>TUNER</id>
                    <value>0</value>
                </gain>
            </gains>
        </device>
        <device>
            <id>HackRF One #0 c83868dc2c4576a3</id>
            <name></name>
            <ppm>0</ppm>
            <offset>0</offset>
            <sample_rate>2000000</sample_rate>
            <agc_mode>1</agc_mode>
            <streamOpts>
                <buffers>15</buffers>
            </streamOpts>
            <settings>
                <bias_tx>true</bias_tx>
            </settings>
            <gains>
                <gain>
                    <id>LNA</id>
                    <value>16</value>
                </gain>
                <gain>
                    <id>VGA</id>
                    <value>16</value>
                </gain>
            </gains>
        </device>
        <device>
            <id>default</id>
            <name></name>
            <ppm>0</ppm>
            <offset>0</offset>
            <sample_rate>0</sample_rate>
            <agc_mode>1</agc_mode>
        </device>
        <device>
            <id>hw:HDA Intel PCH,0</id>
            <name></name>
            <ppm>0</ppm>
            <offset>0</offset>
            <sample_rate>0</sample_rate>
            <agc_mode>1</agc_mode>
        </device>
        <device>
            <id>hw:HDA Intel PCH,2</id>
            <name></name>
            <ppm>0</ppm>
            <offset>0</offset>
            <sample_rate>0</sample_rate>
            <agc_mode>1</agc_mode>
        </device>
        <device>
            <id>hw:Logitech StreamCam,0</id>
            <name></name>
            <ppm>0</ppm>
            <offset>0</offset>
            <sample_rate>0</sample_rate>
            <agc_mode>1</agc_mode>
        </device>
    </devices>
    <rig>
        <enabled>0</enabled>
        <model>1</model>
        <rate>57600</rate>
        <port>/dev/ttyUSB0</port>
        <control>1</control>
        <follow>1</follow>
        <center_lock>0</center_lock>
        <follow_modem>0</follow_modem>
    </rig>
</cubicsdr_config>
```

GDB core dump info

```
 $ gdb /usr/bin/CubicSDR core.431676 
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
/home/oxoocoffee/.gdbinit:7: Error in sourced command file:
Requires an argument. Valid arguments are child, parent.
Reading symbols from /usr/bin/CubicSDR...
(No debugging symbols found in /usr/bin/CubicSDR)
[New LWP 431838]
[New LWP 431679]
[New LWP 431725]
[New LWP 431676]
[New LWP 431730]
[New LWP 431728]
[New LWP 431681]
[New LWP 431839]
[New LWP 431710]
[New LWP 431843]
[New LWP 431682]
[New LWP 431722]
[New LWP 431736]
[New LWP 431678]
[New LWP 431677]
[New LWP 431821]
[New LWP 431734]
[New LWP 431726]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `CubicSDR'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __GI___pthread_mutex_lock (mutex=0x298) at ../nptl/pthread_mutex_lock.c:67
67	../nptl/pthread_mutex_lock.c: No such file or directory.
[Current thread is 1 (Thread 0x7f3f267fc700 (LWP 431838))]

(gdb) where
#0  __GI___pthread_mutex_lock (mutex=0x298) at ../nptl/pthread_mutex_lock.c:67
#1  0x000055c1c4a81960 in AudioThread::run() ()
#2  0x000055c1c4a2f6c2 in IOThread::threadMain() ()
#3  0x00007f3f62238de4 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f3f61fde609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007f3f61f05293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) info threads
  Id   Target Id                          Frame 
* 1    Thread 0x7f3f267fc700 (LWP 431838) 0x000055c1c4a81960 in AudioThread::run() ()
  2    Thread 0x7f3f5db12700 (LWP 431679) 0x00007f3f61ef8aff in __GI___poll (fds=0x55c1c61937e0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  3    Thread 0x7f3edffff700 (LWP 431725) futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f3f3a59a140) at ../sysdeps/nptl/futex-internal.h:183
  4    Thread 0x7f3f5f161ec0 (LWP 431676) 0x00007f3f61ec33bf in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7ffe2c67d9d0, rem=0x7ffe2c67d9d0)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
  5    Thread 0x7f3edcff9700 (LWP 431730) 0x00007f3f61ef8aff in __GI___poll (fds=0x7f3eb8000dc0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  6    Thread 0x7f3edd7fa700 (LWP 431728) 0x00007f3f61ef8aff in __GI___poll (fds=0x7f3eb0001ce0, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  7    Thread 0x7f3f5ca75700 (LWP 431681) 0x00007f3f61ec33bf in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7f3f5ca746e0, rem=0x7f3f5ca746e0)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
  8    Thread 0x7f3f35012700 (LWP 431839) futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7f3f35011560, clockid=<optimized out>, expected=0, futex_word=0x55c1c62f1db4)
    at ../sysdeps/nptl/futex-internal.h:320
  9    Thread 0x7f3f0ffff700 (LWP 431710) 0x00007f3f61ef8aff in __GI___poll (fds=0x7f3f0fffe740, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  10   Thread 0x7f3f3bbff700 (LWP 431843) syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  11   Thread 0x7f3f4ffff700 (LWP 431682) 0x00007f3f61ec33bf in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7f3f4fffe6e0, rem=0x7f3f4fffe6e0)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
  12   Thread 0x7f3ef57fa700 (LWP 431722) futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f3f3a59a280) at ../sysdeps/nptl/futex-internal.h:183
  13   Thread 0x7f3f3929e700 (LWP 431736) 0x00007f3f61ef8aff in __GI___poll (fds=0x7f3f1003c520, nfds=2, timeout=250) at ../sysdeps/unix/sysv/linux/poll.c:29
  14   Thread 0x7f3f5e313700 (LWP 431678) 0x00007f3f61ef8aff in __GI___poll (fds=0x55c1c6181580, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  15   Thread 0x7f3f5eb14700 (LWP 431677) 0x00007f3f61ef8aff in __GI___poll (fds=0x55c1c617f790, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  16   Thread 0x7f3f24ff9700 (LWP 431821) 0x00007f3f61ef8aff in __GI___poll (fds=0x55c1c8933680, nfds=3, timeout=500) at ../sysdeps/unix/sysv/linux/poll.c:29
  17   Thread 0x7f3ea7fff700 (LWP 431734) 0x00007f3f61ef8aff in __GI___poll (fds=0x7f3e98000b60, nfds=2, timeout=250) at ../sysdeps/unix/sysv/linux/poll.c:29
  18   Thread 0x7f3edeffd700 (LWP 431726) 0x00007f3f61efb12b in __GI___select (nfds=74, readfds=0x7f3edeffbf40, writefds=0x0, exceptfds=0x0, timeout=0x7f3edeffbf30)
    at ../sysdeps/unix/sysv/linux/select.c:41
(gdb) list
62	in ../nptl/pthread_mutex_lock.c
(gdb)
```

**Comment by vsonnier** [comment]
Issue is too old, with too old CubicSDR, closing.
